name: Terraform CI

on:
  pull_request:
    branches:
     - main
      
permissions:
  id-token: write
  contents: read 

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./practice
      - name: Terraform Init
        run: terraform init
        working-directory: ./practice
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./practice
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: TFLint Init
        run: tflint --init
        working-directory: ./practice

      - name: TFLint
        run: tflint --recursive
        working-directory: ./practice
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./practice     